version: '3.7'
services:
  react:
    container_name: react
    build:
      context: .
      dockerfile: docker/Dockerfile.local
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 8000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true